### ISSUE TITLE
Performance regression in liquibase  version > 4.4.x 

### ISSUE THREAD

**Issue by menacher** [liquibase/liquibase#2899]
## Environment
JDK 17, Mac OS as well as Alpine Docker and Ubuntu 18.
**Liquibase Version**: 4.11.0

**Liquibase Integration & Version**: Spring boot 2.6.6
**Liquibase Extension(s) & Version**: 

**Database Vendor 
& Version**: Postgres 14

**Operating System Type & Version**: Mac OS, Ubuntu 18, alpine docker.

## Description
See issue #2756 and #2777 for reference. That specific bug with log performance is resolved, however the overall performance itself hasn't improved much. The 4.11.0 version is still 4 times slower than liquibase 4.3.5 version for the same changes initialization.

## Additional Context
Attaching 4.3.5 vs 4.11.0 performance flame graphs for reference.
[Archive.zip](https://github.com/liquibase/liquibase/files/8810662/Archive.zip)

**Comment by nvoxland** [comment]
I opened PR #2914 that helps. Would you be able to use the jar from https://github.com/liquibase/liquibase/actions/runs/2436165606 and see if it helps your setup?

From what I can tell, the cause of the regression is that we fixed the fact that we weren't respecting your `usePreparedStatements="true"` flag in 4.3.5 and are in 4.11.0, but postgresql is being super slow using prepared statements. That surprised me, but is what my profiling was seeing as well.

The PR adds some query flags to postgresql and shifts a couple other thing around to help, but it's still about 2x as long to run using prepared statements vs. regular statements for me. 

So even if that PR does help, I'd suggest taking `usePreparedStatements="true"` off. We have logic in there to use prepared statements when needed (like if you are using blobs) and otherwise use regular statements. Given that postgresql seems faster with the regular statements there is no need to force the prepared statement usage.

**Comment by menacher** [comment]
Hi @nvoxland , that is quite an interesting find. I tried to maven install this jar into local repo and also tried it via the maven `system` scope etc, but in both cases it does not seem to run the changelog at all.
Also, I removed all `usePreparedStatements="true"` from my changelog and tried with the 4.11.0 version and did not see much improvement. When I profiled it, I still see it is using the Postgres preparedStatements even though this flag is not present.
I will wait for 4.12 version to come in with this
[no_usepreparedstmt_4.11.0.html.zip](https://github.com/liquibase/liquibase/files/8836975/no_usepreparedstmt_4.11.0.html.zip)
 fix and try again.

**Comment by menacher** [comment]
@nvoxland This worked great! 
**4.11.0 version**
Started DemoApplication in 46.998 seconds (JVM running for 49.536)
Started DemoApplication in 46.127 seconds (JVM running for 48.787)
Started DemoApplication in 45.565 seconds (JVM running for 48.481)


**4.3.5 version**
Started DemoApplication in 43.784 seconds (JVM running for 46.568)
Started DemoApplication in 42.345 seconds (JVM running for 45.206)
Started DemoApplication in 42.878 seconds (JVM running for 45.595)

**Comment by nvoxland** [comment]
Thanks, @menacher. Still weird about the slow prepared statement peformance on postgreql. I'll see about maybe not using them on postgresql if usePreparedStatements is not specified.
