### ISSUE TITLE
Database Exception Error Fetching enum values

### ISSUE THREAD

**Issue by tinah-1973** [liquibase/liquibase#3734]
## Environment

**Liquibase Version**: 4.19.0

**Liquibase Integration & Version**: Spring Boot 3

**Database Vendor & Version**: MySQL 8.0.30

## Description

During the build process an exception is thrown for enum declared columns 
in the class ColumnSnapshotgenerator, line 425
with the following output:
```
liquibase.exception.DatabaseException: Error executing SQL SELECT DISTINCT SUBSTRING_INDEX(SUBSTRING_INDEX(SUBSTRING(COLUMN_TYPE, 7, LENGTH(COLUMN_TYPE) - 7 - 1 ), "','", 1 + units.i + tens.i * 10) , "','", -1)
FROM INFORMATION_SCHEMA.COLUMNS
CROSS JOIN (SELECT 0 AS i UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) units
CROSS JOIN (SELECT 0 AS i UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) tens
WHERE TABLE_SCHEMA = 'my_table_schema'
AND TABLE_NAME = 'InfoContent'
AND COLUMN_NAME = 'Type'
ORDER BY tens.i, units.i: Expression #1 of ORDER BY clause is not in SELECT list, references column 'tens.i' which is not in SELECT list; this is incompatible with DISTINCT
 ```

This is the corresponding column definition

```
<column defaultValue="DEFAULT" name="Type" type="ENUM('DEFAULT', 'PRODUCT_API')">
                <constraints nullable="false"/>
</column>
```

Is the column definition wrong or is something missing?

**Comment by FBurguer** [comment]
Hi! We dont support the column type enum as you can see [here](https://docs.liquibase.com/change-types/nested-tags/column.html)  if you want to create or manipulate a column with enum type you should do a use the sql change type. Thanks for submittion this issue. In case this doesnt help let us know, I will leave this issue open until then.

**Comment by sttuartt** [comment]
Does that mean you don't support ENUM columns when running the `generate-changelog` command either?

If I run a `liquibase generate-changelog` against my MySQL database, I get output similar to the following for ENUM columns:
```
            <column name="status" type="ENUM(11)">
                <constraints nullable="false"/>
            </column>
```
.. when it should be:
```
            <column name="status" type="ENUM('FAILED', 'CANCELLED', 'INGEST', 'IN_PROGRESS', 'COMPLETE')">
                <constraints nullable="false"/>
            </column>
```
Based on [this very old thread](https://forum.liquibase.org/t/generatechangelog-does-not-work-with-enum/2772), it was supposedly fixed in version 3.0.8 - has it regressed? Or is this a new bug? Or is this be design for some reason?

Thanks.

**Comment by tinah-1973** [comment]
I created the enum column with a native SQL statement

```
 <changeSet id="addEnumTypeColumnForInfoContent" author="tina">
        <sql>ALTER TABLE InfoContent
            ADD COLIUMN Type ENUM('DEFAULT', 'PRODUCT_API') DEFAULT 'DEFAULT' NOT NULL</sql>
    </changeSet>
```
The column is created correctly
But the database exception from above still occurs.

**Comment by FBurguer** [comment]
It looks like you are right and this is indeed a bug. I will add it to our queue of issues to fix. It can take a while to fix, now that you have an idea of what could be happening, can you submit a PR with a fix? This will speed up the process and we will help you through it. Thanks!

**Comment by nwcm** [comment]
Came here to see if this had been raised. Seeing the same thing `fieldName ENUM(10) NULL, ` over the correct values

**Comment by nwcm** [comment]
@FBurguer I made some quick changes, but I'm not really across the expected operation of this or JAVA. Not sure why you'd want to reforge the string when MySQL provides in in the correct `enum('value1','value2')` format.

I haven't built or tested as i don't have time to learn to build the java right now. But hopefully someone with experience can 

https://github.com/liquibase/liquibase/pull/3832/files

**Comment by nwcm** [comment]
> It looks like you are right and this is indeed a bug. I will add it to our queue of issues to fix. It can take a while to fix, now that you have an idea of what could be happening, can you submit a PR with a fix? This will speed up the process and we will help you through it. Thanks!

Had a second go and fixed this up. It is working in generateChangeLog for me 

https://github.com/liquibase/liquibase/pull/3842/files

**Comment by thymepuns** [comment]
Looks like this was introduced in #3150 
I reverted to 4.10.0 and I don't have the issue (but the sorting is indeed wrong).
@nwcm have you tried removing the entire if block? I don't know the code well, but it seems like the MySQL workaround that was needed 10 years ago (https://github.com/liquibase/liquibase/commit/fa6cd1d5413d51749ce05edb6c79f60d12784daf) is no longer needed. But not sure since enum isn't standard what else is needed. https://liquibase.jira.com/browse/CORE-1224 implies it was needed at least as late as MySQL 5.5. But http://download.nust.na/pub6/mysql/doc/refman/5.5/en/enum.html implies that it should have worked without this strange workaround.
